# -*- coding: utf-8 -*-
"""G-1A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6_hqd-Mp6rYDz4KYnPIddxevN7tWmBK
"""

def largest(numbers) :

  highest = numbers[0]

  for i in range(len(numbers)):
    if numbers[i] > highest :
      highest = numbers[i]


  return highest

num = [10,40,23,90,22,45,2]

mx_n = largest(num)

print(mx_n)