# -*- coding: utf-8 -*-
"""G-1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ly8rR_o9OZWPUMyXps7yFpJniq50Udrv
"""

def even(numbers) :

  count = 0
  for num in numbers :
    if num % 2 == 0 :
      count += 1

  return count

numbers = [1,2,3,4,5,6,6,7,8,9,10]
print(even(numbers))