# -*- coding: utf-8 -*-
"""G-1C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8HD-kVyB6Ht1-PLX60wZBC3VPFJK1DC
"""

def fre_count(str) :

  count = {}

  for ch in str:

    if ch == ' ':

      continue

    if ch not in count :

      count[ch] = 1

    else:

      count[ch] += 1

  return count

print(fre_count("hello world"))